version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/js_modules/dagster-ui"
    schedule:
      interval: "daily"
    reviewers:
      - "hellendag"
      - "salazarm"
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/python_modules/dagster"
    schedule:
      interval: "daily"
    reviewers:
      - "dagster-io/oss"
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/python_modules/dagster-graphql"
    schedule:
      interval: "daily"
    reviewers:
      - "dagster-io/oss"
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/python_modules/dagster-webserver"
    schedule:
      interval: "daily"
    reviewers:
      - "dagster-io/oss"
    open-pull-requests-limit: 0
